[package]
name = "sparse"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33.0", optional = true }
rand = "0.8.5"
rayon = "1.10.0"

[[bin]]
name = "benchmark"

[profile.release]
debug = 1

[features]
nalgebra = ["dep:nalgebra"]
